### ISSUE TITLE
Extension seems to be broken for VSCode >= 1.61.2

### ISSUE THREAD

**Issue by binaryunary** [flobilosaurus/vscode-asciidoc-slides#31]
Nothing happens when I trigger any of the extension actions. 

The following error appears in the console (visible in the dev tools):

```
console.ts:137 [Extension Host] stack trace: TypeError: $.$== is not a function
	at constructor.f (/home/user/.vscode/extensions/flobilosaurus.vscode-asciidoc-slides-1.3.0/dist/extension.js:390:812188)
	at Object.Opal.send (/home/user/.vscode/extensions/asciidoctor.asciidoctor-vscode-2.8.10/node_modules/asciidoctor-opal-runtime/src/opal.js:1671:19)
	at Function.$Class_new$5 (/home/user/.vscode/extensions/asciidoctor.asciidoctor-vscode-2.8.10/node_modules/asciidoctor-opal-runtime/src/opal.js:3638:12)
	at Function.$$create (/home/user/.vscode/extensions/asciidoctor.asciidoctor-vscode-2.8.10/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:7226:37)
	at constructor.$$create_converter (/home/user/.vscode/extensions/asciidoctor.asciidoctor-vscode-2.8.10/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:8743:78)
	at constructor.$$update_backend_attributes (/home/user/.vscode/extensions/asciidoctor.asciidoctor-vscode-2.8.10/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:8996:97)
	at constructor.$$initialize (/home/user/.vscode/extensions/asciidoctor.asciidoctor-vscode-2.8.10/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:7875:16)
	at Object.Opal.send (/home/user/.vscode/extensions/asciidoctor.asciidoctor-vscode-2.8.10/node_modules/asciidoctor-opal-runtime/src/opal.js:1671:19)
	at Function.$Class_new$5 (/home/user/.vscode/extensions/asciidoctor.asciidoctor-vscode-2.8.10/node_modules/asciidoctor-opal-runtime/src/opal.js:3638:12)
	at /home/user/.vscode/extensions/asciidoctor.asciidoctor-vscode-2.8.10/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:16262:45
	at Function.$$load (/home/user/.vscode/extensions/asciidoctor.asciidoctor-vscode-2.8.10/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:16263:28)
	at Function.$$convert (/home/user/.vscode/extensions/asciidoctor.asciidoctor-vscode-2.8.10/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:16404:20)
	at Function.Asciidoctor.convert (/home/user/.vscode/extensions/asciidoctor.asciidoctor-vscode-2.8.10/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:21890:21)
	at t.RevealSlides.convertToRevealJsSlides (/home/user/.vscode/extensions/flobilosaurus.vscode-asciidoc-slides-1.3.0/dist/extension.js:390:10188)
	at new t.RevealSlides (/home/user/.vscode/extensions/flobilosaurus.vscode-asciidoc-slides-1.3.0/dist/extension.js:390:10009)
	at new t.Container (/home/user/.vscode/extensions/flobilosaurus.vscode-asciidoc-slides-1.3.0/dist/extension.js:176:47557)
	at t.ContainerManager.getOrCreateContainer (/home/user/.vscode/extensions/flobilosaurus.vscode-asciidoc-slides-1.3.0/dist/extension.js:176:46856)
	at t.ContainerManager.<anonymous> (/home/user/.vscode/extensions/flobilosaurus.vscode-asciidoc-slides-1.3.0/dist/extension.js:176:46626)
	at Generator.next (<anonymous>)
	at /home/user/.vscode/extensions/flobilosaurus.vscode-asciidoc-slides-1.3.0/dist/extension.js:176:46268
	at new Promise (<anonymous>)
	at n (/home/user/.vscode/extensions/flobilosaurus.vscode-asciidoc-slides-1.3.0/dist/extension.js:176:46013)
	at Object.andDo (/home/user/.vscode/extensions/flobilosaurus.vscode-asciidoc-slides-1.3.0/dist/extension.js:176:46491)
	at Object.t.showPreview (/home/user/.vscode/extensions/flobilosaurus.vscode-asciidoc-slides-1.3.0/dist/extension.js:176:43193)
	at /home/user/.vscode/extensions/flobilosaurus.vscode-asciidoc-slides-1.3.0/dist/extension.js:176:41307
	at l._executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:111652)
	at l.$executeContributedCommand (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:112090)
	at i._doInvokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:13802)
	at i._invokeHandler (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:13486)
	at i._receiveRequest (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:12148)
	at i._receiveOneMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:10826)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98:8922
	at a.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
	at l.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:15990)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:30514
	at a.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
	at l.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:15990)
	at u._receiveMessage (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:21260)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:18138
	at a.fire (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66:1712)
	at w.acceptChunk (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:13351)
	at /usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74:12699
	at Socket.v (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:13465)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23)
```

**Comment by rillbert** [comment]
I see the same behavior for v1.61.1 (on Ubuntu 20.04)

**Comment by flobilosaurus** [comment]
Hi there, first of all sorry for long response time. The source of the bug seems to be the asciidoctor-vscode extension. It will be fixed in the near future. You can track the state of the issue here: https://github.com/asciidoctor/asciidoctor-vscode/issues/478

**Comment by flobilosaurus** [comment]
Hi @rillbert, the latest update of asciidoc-vscode extension to version 2.9.4 fixed asciidoc-slides plugin on my machine. Can u verify that?

**Comment by rillbert** [comment]
I’m away this week but I’ll try it out during the coming week. 

Cheers
/Anders 

Skickat från min iPhone

**Comment by bentolor** [comment]
Plugin works for me in latest VS Code. Guess this issue can be closed.
